//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTraffic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumptionRecord
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> Obj_ID { get; set; }
        public string Obj_Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public decimal RealMoney { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> ReturnMoney { get; set; }
    }
}
