//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTraffic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrafficEntities : DbContext
    {
        public TrafficEntities()
            : base("name=TrafficEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConsumptionRecord> ConsumptionRecord { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Recharge> Recharge { get; set; }
        public virtual DbSet<TaskRecord> TaskRecord { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Task> Task { get; set; }
    }
}
