//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTraffic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> Moneys { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string FromType { get; set; }
        public string Remarks { get; set; }
        public string OtherOrderNum { get; set; }
        public string OrderNum { get; set; }
    }
}
