//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTraffic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskRecord
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public string TaskTitle { get; set; }
        public int OpUserID { get; set; }
        public string OPUserName { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> ReadNum { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> PraiseNum { get; set; }
        public Nullable<decimal> Consumption { get; set; }
        public Nullable<decimal> ReturnNum { get; set; }
        public Nullable<decimal> Choice { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
